name: esmail_clinic_app
description: Esmail Clinic Arabic booking app (RTL + embedded Arabic font)
publish_to: "none"
version: 1.4.0+7

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
  fonts:
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/NotoNaskhArabic-Regular.ttf
        - asset: assets/NotoNaskhArabic-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/app_icon.png
